<?php

namespace ContainerE2Iw4ok;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPanierConfirmationTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\PanierConfirmationType' shared autowired service.
     *
     * @return \App\Form\PanierConfirmationType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/PanierConfirmationType.php';

        return $container->privates['App\\Form\\PanierConfirmationType'] = new \App\Form\PanierConfirmationType();
    }
}
