<?php

namespace ContainerTLDVq6o;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_YNO4FUyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.YNO4FUy' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.YNO4FUy'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'products' => ['privates', 'App\\Repository\\ProductRepository', 'getProductRepositoryService', true],
        ], [
            'products' => 'App\\Repository\\ProductRepository',
        ]);
    }
}
