<?php

namespace ContainerXHUIKUl;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Tg1sQTService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator._Tg1sQT' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator._Tg1sQT'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'session' => ['privates', '.errored..service_locator._Tg1sQT.Symfony\\Component\\HttpFoundation\\Session\\Session', NULL, 'Cannot autowire service ".service_locator._Tg1sQT": it references class "Symfony\\Component\\HttpFoundation\\Session\\Session" but no such service exists.'],
            'userRepository' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
        ], [
            'session' => 'Symfony\\Component\\HttpFoundation\\Session\\Session',
            'userRepository' => 'App\\Repository\\UserRepository',
        ]);
    }
}
