<?php

namespace ContainerIUPobIn;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPurchaseConfirmationControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\Purchase\PurchaseConfirmationController' shared autowired service.
     *
     * @return \App\Controller\Purchase\PurchaseConfirmationController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/Purchase/PurchaseConfirmationController.php';
        include_once \dirname(__DIR__, 4).'/src/Panier/PanierService.php';

        $container->services['App\\Controller\\Purchase\\PurchaseConfirmationController'] = $instance = new \App\Controller\Purchase\PurchaseConfirmationController(new \App\Panier\PanierService(($container->privates['App\\Repository\\ProductRepository'] ?? $container->load('getProductRepositoryService'))), ($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService()));

        $instance->setContainer(($container->privates['.service_locator.jIxfAsi'] ?? $container->load('get_ServiceLocator_JIxfAsiService'))->withContext('App\\Controller\\Purchase\\PurchaseConfirmationController', $container));

        return $instance;
    }
}
