<?php

namespace Container6p0oxi0;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_1U1z2JhService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.1U1z2Jh' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.1U1z2Jh'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'session' => ['privates', '.errored..service_locator.1U1z2Jh.Symfony\\Component\\HttpFoundation\\Session\\Session', NULL, 'Cannot autowire service ".service_locator.1U1z2Jh": it references class "Symfony\\Component\\HttpFoundation\\Session\\Session" but no such service exists.'],
            'userRepository' => ['privates', 'App\\Repository\\ClientRepository', 'getClientRepositoryService', true],
        ], [
            'session' => 'Symfony\\Component\\HttpFoundation\\Session\\Session',
            'userRepository' => 'App\\Repository\\ClientRepository',
        ]);
    }
}
