<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTLDVq6o\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTLDVq6o/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerTLDVq6o.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerTLDVq6o\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerTLDVq6o\App_KernelDevDebugContainer([
    'container.build_hash' => 'TLDVq6o',
    'container.build_id' => '2c845549',
    'container.build_time' => 1649803942,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTLDVq6o');
