<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerP8fAskR\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerP8fAskR/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerP8fAskR.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerP8fAskR\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerP8fAskR\App_KernelDevDebugContainer([
    'container.build_hash' => 'P8fAskR',
    'container.build_id' => 'e942a901',
    'container.build_time' => 1649794574,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerP8fAskR');
