<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTueJGxG\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTueJGxG/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerTueJGxG.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerTueJGxG\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerTueJGxG\App_KernelDevDebugContainer([
    'container.build_hash' => 'TueJGxG',
    'container.build_id' => '0e6dd190',
    'container.build_time' => 1655078516,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTueJGxG');
